export enum ErrorCodes {
  SERVER_ERROR = 1000,
  INVALID_REGISTRATION_CREDENTIALS,
  INVALID_AUTHORIZATION_CREDENTIALS,
  USERNAME_ALREADY_EXISTS,
  USER_NOT_FOUND,
  INVALID_PASSWORD,
  INVALID_CREATION_TODO_DTO,
  INVALID_UPDATE_TODO_DTO,
  INVALID_REMOVE_TODO_DTO,
  TODO_NOT_FOUND,
  INVALID_ASSIGNED_USER_ID,
  USERNAME_NOT_FOUND,
}
